name: My GitHub Actions Workflow

on:
  push:
    branches: [ developer ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clear yarn cache
      run: yarn cache clean --force

    - name: Remove node_modules folder
      run: rm -rf node_modules

    - name: Install dependencies
      run: yarn

      - name: Build the app
        run: yarn build
      
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exclude '.DS_Store' --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_KEY_ID: ${{ secrets.AWS_S3_KEY_ID }}
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'build'
