name: Upload Website

on: 
  push:
    branches:
      - developer

jobs:
  deploy:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn
      - run: CI='' yarn build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_KEY_ID: ${{ secrets.AWS_S3_KEY_ID }}
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'build'
